---
- name: Baseline host
  hosts: all
  tasks:
    - name: "Install Datadog Packages"
      ansible.builtin.include_role:
        name: datadawg
      vars:
        datadawg_env_vars: "{{ vagrant.datadog }}"
        datadawg_install_datadog_agent: true
        datadawg_install_datadog_agent_via_script: false
        datadawg_install_datadog_agent_via_official_role: true
        datadawg_install_vector_agent: true

    # - name: "Configure SSH"
    # TODO

    # TODO
    - name: Configure Ansible User
      hosts: all
      tasks:
        # - name: "Create group"
        #
        - name: "Create user"
          ansible.builtin.include_role:
            name: users
          vars:
            users_all:
              - user: "ansible" # TODO: Update with variable
                # Encrypted hash (Linux) or plain text password (macOS).
                # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
                # To create an account with a locked/disabled password on Linux systems, set this to '!' or '*'.
                # To create an account with a locked/disabled password on OpenBSD, set this to '*************'.
                # OS X/macOS: Enter the cleartext password as the value. Be sure to take relevant security precautions.
                password: "ansible" # TODO: Update with variable
                # groups: [] # TODO: Update with variable from group creation task
                is_system_user: false
                home_directory:
                  path: "/home/ansible" # TODO: Update with variable
                  create: true
                  move: false
                # See SSH Keygen
                ssh_key:
                  generate: false
                  type: ed25519
                  bits: 4096
                  passphrase: "" # TODO: Update with variable
                  filepath: "~/.ssh/id_ed25519"
                  comment: "" # TODO: Update with variable
