name: "Datadog Examples Workflow"
run-name: "${{ github.actor }} is testing out GitHub Actions"
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo Hello world!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Datadog Service Catalog Metadata Provider"
        uses: "arcxp/datadog-service-catalog-metadata-provider@v2.0.0"
